### PR TITLE
Implement function 'GetApplicationStep'

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
Implements function `GetApplicationStep`

- Adds models `ApplicationStep`, `Environment`, `Operator`, `AccessLevel`
- Updates existing models `PortfolioDraft`, `FileMetadata` per the API spec
- Adds step key constants `PORTFOLIO_STEP`, `FUNDING_STEP`, `APPLICATION_STEP` to model `PortfolioDraft` so they can be referenced by functions
- Updates existing functions to reference the aforementioned step key constants
- Defines function and adds to stack
- Adds GET method to new route '/portfolioDrafts/{portfolioDraftId}/application'
- Adds unit test for function

Ticket: AT-6466

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
This is ready for review.  Plan to add more tests.  At 50% test coverage currently.

**Review by kylelaker-ccpo — APPROVED** [review]

**Comment by kylelaker-ccpo** [comment]
Approved with the expectation that the additional tests will be added.

**Comment by jasonburkert-ccpo** [comment]
image

**Comment by jasonburkert-ccpo** [comment]
At 95% test coverage.

**Pull request merged**
