### PR TITLE
Improvements to Evaluation Plan template

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
Improves Evaluation Plan template
- Implements a business rule for assessment area _Risk to the Government_ when the method is `LOWEST_RISK`
  - This is done in a manner similar to what is done on the UI (_required_ compliance standards and assessment areas exist only in the UI and in the template and not in the database)
- Wraps each `FOR` tag in `IF` conditional to prevent doc gen failure on nulls
- Makes consistent use of bullet styles
- Makes 28 very minor changes.  These include things such as removal of spaces at the end of lines, spaces within logic tags, and normalizing spaces used in table headings.

Ticket: AT-8610

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
Addresses the yellow highlighted areas, except for the varying bullet styles.
21410014-ef89-4aae-ad60-9b2448989a20

**Comment by jasonburkert-ccpo** [comment]
Implements this business rule when method is `LOWEST_RISK`

image

Omits repeating the output of the same assessment area if one should slip into the optional collection, even though the UI prevents it.

image

**Comment by jasonburkert-ccpo** [comment]
### Made bullet styles uniform

Before

3d2b5e8b-c34f-45d3-b5fc-1e7531dd6aba

After

image

**Comment by jasonburkert-ccpo** [comment]
### Fixes the following doc gen error

Wrapped each FOR tag in IF conditional to prevent doc gen failure on nulls

image

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Document looks good and generates with the expected behavior.

**Pull request merged**
