### PR TITLE
Enable API Gateway access logs

### PR DESCRIPTION
**Pull request by kylelaker-ccpo**
This enables access logs in addition to the execution logs that we had
previously. This will provide additional information and context around
requests.

### CODE REVIEW

**Review by juliusfitzhugh-ccpo — APPROVED** [review]
Nice, this will surely help provide more useful information in logs. I accidentally did this previously in a ticket and removed. I used a custom format. Below is what I did previously, and this does not have to be included, I just wanted share incase we want to include additionally details now or in the future. 

```typescript
    const {
      contextRequestTime,
      contextRequestId,
      contextHttpMethod,
      contextPath,
      contextResourcePath,
      contextStatus,
      contextResponseLatency,
      contextIntegrationStatus,
      contextIntegrationLatency,
      contextIdentitySourceIp,
      contextIdentityUserAgent,
      contextIdentityCaller,
      contextIdentityUser,
      contextAccountId,
      contextApiId,
      contextStage,
    } = apigw.AccessLogField;

 // custom format to add your own information   
accessLogFormat: apigw.AccessLogFormat.custom(
`{"requestTime":"${contextRequestTime()}",
"requestId":"${contextRequestId()}",
"httpMethod":"${contextHttpMethod()}",
"path":"${contextPath()}",
"resourcePath":"${contextResourcePath()}",
"status":${contextStatus()},
"responseLatency":${contextResponseLatency()},
"functionResponseStatus":"${contextIntegrationStatus()}",
"integrationRequestId":"$context.integration.requestId",
"integrationLatency":"${contextIntegrationLatency()}",
"ip":"${contextIdentitySourceIp()}",
"userAgent":"${contextIdentityUserAgent()}",
"caller":"${contextIdentityCaller()}",
"user":"${contextIdentityUser()}",
"accountId":"${contextAccountId()}",
"apiId":"${contextApiId()}",
"stage":"${contextStage()}"}\n`
        ),

**Comment by kylelaker-ccpo** [comment]
I'll play with that. Going to move this to draft to prevent merging. We may want a few of those fields.

**Review by juliusfitzhugh-ccpo — COMMENTED** [review]
Looks good to me! And just as a reference, the work I previously did was inspired by [API Gateway access logs](https://www.alexdebrie.com/posts/api-gateway-access-logs/) by Alex DeBrie.

**Comment by kylelaker-ccpo** [comment]
> Looks good to me! And just as a reference, the work I previously did was inspired by [API Gateway access logs](https://www.alexdebrie.com/posts/api-gateway-access-logs/) by Alex DeBrie.

Thanks for that link! https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html#context-variable-reference are the official docs from AWS too. But that page definitely seems to make things more accessible.

**Pull request merged**
