### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by juliusfitzhugh-ccpo**

### CODE REVIEW

**Comment by kylelaker-ccpo** [comment]
Oof not sure what's up with that build failure

**Comment by juliusfitzhugh-ccpo** [comment]
@kylelaker-ccpo okay, so it's not just me I was trying to wrap my mind around the issue, no luck either.

**Comment by kylelaker-ccpo** [comment]
It looks like maybe `npm update` bumped the version of `yargs-parser`? Maybe that's (part of) the issue? Not really sure. But it definitely seems related to the error message.

**Comment by kylelaker-ccpo** [comment]
Ahh yeah https://github.com/yargs/yargs-parser/issues/452 seems related

**Comment by juliusfitzhugh-ccpo** [comment]
yeah, that definitely is the same error we're getting. Do we just wait for that issue to be fixed? Or is there something else we can do?

**Comment by kylelaker-ccpo** [comment]
How did I end up with merge conflicts when I did that? Okay... uhh lemme work that out.

**Comment by juliusfitzhugh-ccpo** [comment]
Thanks for the additions! Looks like the issue was fixed for `yargs-parser`. I would approve, but not allowed 😆.
@jeffsaunders-hacc @zachclark-ccpo can one of you approve this PR?

**Review by kylelaker-ccpo — APPROVED** [review]
I'm good with just approving. It's dependencies only and if we're both good with the changes, I think that's sufficient.

**Pull request merged**
