### PR TITLE
Reorganize microservices

### PR DESCRIPTION
**Pull request by jasonburkert-ccpo**
Reorganizes implementation files for microservices for increased clarity.
The catalyst for this was a discussion about where files for route `/taskOrderFiles` will live in support of ticket AT-6417.
This change enacts the following structure envisioned by today's discussion:

```
./infrastructure/
./microservices/package.json
./microservices/utils/
./microservices/models/
./microservices/api/portfolioDrafts/
./microservices/api/taskOrderFiles/
```

- [x] rename `applications` dir to `microservices`
- [x] add `api` dir to contain `portfolioDrafts` and `taskOrderFiles`
- [x] relocate `utils` and `models` dirs parallel to `api` dir
- [x] adjust lerna configuration
- [x] adjust existing file content (import references, etc)
- [x] ensure transpiles with tsc
- [x] adjust github workflow
- [x] adjust package scripts 
- [x] deploy
- [x] test thoroughly

### CODE REVIEW

**Comment by jasonburkert-ccpo** [comment]
Deployed stack and tested all existing functions.   Verified behavior is as expected.

**Review by jeffsegal-ccpo — CHANGES_REQUESTED** [review]
I would say that right now we are really deploying a single microservice, which is the entire internal API. So you could even say that this makes `atat-web-api` a monorepo. If we're in agreement there, then the only change I might make is `s/microservices/microservice` since we are not planning on adding another one here.

**Comment by jasonburkert-ccpo** [comment]
Captured this direction during today's conversation.

TARGET STRUCTURE TODAY
```
./infrastructure/
./infrastructure/package.json

./packages/api/
./packages/api/package.json
./packages/api/portfolioDrafts/
./packages/api/taskOrderFiles/
./packages/api/utils/
./packages/api/models/

./packages/filescanner/
./packages/filescanner/package.json
```

FUTURE MODIFICATIONS - Move `models` to it's own shareable package
```
./packages/models/
./packages/models/package.json
```

**Comment by jasonburkert-ccpo** [comment]
Will replace with new PR.

**Pull request closed without merging**
